### ISSUE TITLE
Upload files to PyPi show 'SignatureDoesNotMatch' errors

### ISSUE THREAD

**Issue by bpepple** [JRubics/poetry-publish#21] opened 2022-06-02 22:11 UTC
This GH action worked fine in the past (last file published April 5), but current uploads show the 'SignatureDoesNotMatch' for the uploaded files. My PyPi Secrets hasn't changed since the last time I published a release.

Didn't notice any discernable errors in the gh action logs, but here's the tail of the build & publish log.

```
Installing the current project: metron-tagger (1.2.6)
Building metron-tagger (1.2.6)
  - Building sdist
  - Built metron-tagger-1.2.6.tar.gz
  - Building wheel
  - Built metron_tagger-1.2.6-py3-none-any.whl
No suitable keyring backends were found
Using a plaintext file to store and retrieve credentials

No suitable keyring backends were found
Publishing metron-tagger (1.2.6) to PyPI
Using a plaintext file to store and retrieve credentials
 - Uploading metron-tagger-1.2.6.tar.gz 0%
 - Uploading metron-tagger-1.2.6.tar.gz 21%
 - Uploading metron-tagger-1.2.6.tar.gz 100%

 - Uploading metron-tagger-1.2.6.tar.gz 100% - Uploading metron_tagger-1.2.6-py3-none-any.whl 0%
 - Uploading metron_tagger-1.2.6-py3-none-any.whl 100%

 - Uploading metron_tagger-1.2.6-py3-none-any.whl 100%
```

**Comment by JRubics** [comment] 2022-06-02 22:14
Can you please try to specify the action version to v1.10 if you are using latest, so I can be sure that the previous version was working for you and the problem is in the current one?

**Comment by bpepple** [comment] 2022-06-02 22:19
First time I tried to publish was with v1.9 (which is what I used in April) & then I tried again with v1.11, both had the same result.

**Comment by bpepple** [comment] 2022-06-02 22:23
This may be a PyPi issue: https://github.com/pypa/warehouse/issues/11500

**Comment by JRubics** [comment] 2022-06-02 22:27
Most likely yes, since the version v1.9 of the action definitely wasn't changed since you last time used it.  Closing this issue, since it is no relevant for this repo. Hope it will be solved soon! :)

**Closed by JRubics** 2022-06-02 22:27 UTC
